Test and adjust the bootstrap and purge scripts.

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -1,16 +1,10 @@
 #!/bin/sh
 
-touch README
-touch ABOUT-NLS
-
 mkdir -p m4
 
-echo "Running aclocal..." ; aclocal $ACLOCAL_FLAGS -I m4 || exit 1
+echo "Running aclocal..." ; aclocal -I m4 || exit 1
 echo "Running autoheader..." ; autoheader || exit 1
 echo "Running autoconf..." ; autoconf || exit 1
 echo "Running libtoolize..." ; (libtoolize --copy --automake || glibtoolize --automake) || exit 1
-echo "Running automake..." ; automake --add-missing --copy --gnu || exit 1
-
-if [ -z "$NOCONFIGURE" ]; then
-	./configure -C "$@"
-fi
+echo "Running automake..." ; automake --add-missing --copy || exit 1
+echo "Running autoreconf..." ; autoreconf || exit 1
